# Ranges are [min, max], with both inclusive
general:
  include_dates: ["2016-10-03", "2016-10-03"] # Use YYYY-MM-DD format
  include_heights: [200, 3999]
radars:
  seang:
#  searl:
#  sease:
#  sehud:
aggregation:
timamp:
flowviz:
