# Ranges are [min, max], with both inclusive
general:
  include_dates: ["2016-10-03", "2016-10-03"] # Use YYYY-MM-DD format
  include_heights: [200, 1200]
radars:
  seang:
    include_heights: [400, NA]
 
  searl:
#  sease:
#  sehud:
timamp:
flowviz:
