---
title: "Aggregate vertical profile data (from CSV)"
author: "Peter Desmet"
output:
  html_document:
    toc: yes
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, results="hide", warning=FALSE, message=FALSE}
library(dplyr)
library(lubridate)
```

## 1. Read data from CSV file

```{r read_csv}
vpdf <- read.csv(file = "../data/interim/vp.csv")
head(vpdf)
```

Interpret `date_time` as POSIXct rather than factor:

```{r cast_date}
vpdf %>% mutate(date_time = as.POSIXct(date_time, format = "%Y-%m-%d %H:%M:%S")) -> vpdf
```

```{r head_data}
head(vpdf)
```

Number of records:

```{r count_data}
nrow(vpdf)
```

## 2. Filter out lower and upper heights

Not all radars will have data below 200m or above 4000m (see https://github.com/enram/timamp-etl/issues/9), so we only keep data from the **200-3800m height range** (both inclusive, resulting in 19 heights):

```{r filter_heights}
vpdf %>% dplyr::filter(HGHT >= 200 & HGHT <= 3800) -> vpdf
nrow(vpdf)
```

## 3. Add aggregation bins

```{r add_bins}
vpdf %>%
# bin date_time on hour:
dplyr::mutate(date_time_bin = format(floor_date(date_time, unit = "hour"), "%Y%m%d %H%M")) %>%

# bin HGHT in 4 bins:
dplyr::mutate(height_bin = case_when(
  .$HGHT < 200 ~ "200 and below", # are filtered out
  .$HGHT >= 200 & .$HGHT < 1000 ~ "0200-1000",  # 4 heights
  .$HGHT >= 1000 & .$HGHT < 2000 ~ "1000-2000", # 5 heights
  .$HGHT >= 2000 & .$HGHT < 3000 ~ "2000-3000", # 5 heights
  .$HGHT >= 3000 & .$HGHT < 4000 ~ "3000-4000", # 5 heights
  .$HGHT >= 4000 ~ "4000 and above" # are filtered out
)) -> vpdf
```

```{r head_bins}
head(vpdf)
```

## 4. Aggregate data

